# Generated by Django 3.2.7 on 2021-09-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=99, null=True)),
                ('city', models.CharField(blank=True, max_length=99, null=True)),
                ('track_name', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'db_table': 'Track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='events.track')),
                ('year', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=99, null=True)),
                ('city', models.CharField(blank=True, max_length=99, null=True)),
                ('track_name', models.CharField(blank=True, max_length=99, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('track_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Event',
                'managed': False,
            },
        ),
    ]
